WebApp3/WebApp3/Models/ErrorViewModel.cs
using System;

namespace WebApp3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp3/WebApp3/Models/QuizAnswerModel.cs
using WebApp3.Utils;

namespace WebApp3.Models
{
    public class QuizAnswerModel
    {
        [LessThanOrNull(101, ErrorMessage = "Здесь не может быть такого большого числа")]
        public int? Answer { get; set; }
    }
}

WebApp3/WebApp3/Models/QuizQuestionModel.cs
using System;
using Microsoft.AspNetCore.Hosting;

namespace WebApp3.Models
{
    public class QuizQuestionModel
    {
        public int X { get; set; }
        public int Y { get; set; }
        public string Operation { get; set; }

        public int CorrectAnswer
        {
            get
            {
                return Operation switch
                {
                    "+" => X + Y,
                    "-" => X - Y,
                    "*" => X * Y,
                    "/" when Y != 0 => X / Y,
                    "/" when Y == 0 => throw new Exception("Dividing by zero"),
                    _ => throw new Exception("Invalid operation")
                };
            }
        }

        public int? UserAnswer { get; set; }

        public bool AnswerIsCorrect
        {
            get { return UserAnswer is { } a && a == CorrectAnswer; }
        }

        public override string ToString()
        {
            return Operation switch
            {
                "+" => $"{X} + {Y} = ",
                "-" => $"{X} - {Y} = ",
                "*" => $"{X} * {Y} = ",
                "/" when Y != 0 => $"{X} / {Y} = ",
                "/" when Y == 0 => throw new Exception("Dividing by zero"),
                _ => throw new Exception("Invalid operation")
            };
        }

        public static QuizQuestionModel RandomQuizQuestion
        {
            get
            {
                var random = new Random();
                return new QuizQuestionModel
                {
                    X = random.Next(0, 10),
                    Y = random.Next(1, 10),
                    Operation = random.Next(4) switch
                    {
                        0 => "+",
                        1 => "-",
                        2 => "*",
                        3 => "/",
                        _ => throw new Exception("Random number is too big")
                    }
                };
            }
        }
    }
}

WebApp3/WebApp3/Models/QuizResultModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp3.Models
{
    public class QuizResultModel
    {
        public List<QuizQuestionModel> Questions { get; set; }

        public int CorrectAnswerCount
        {
            get
            {
                return Questions.Count(q => q.AnswerIsCorrect);
            }
        }

        public int Count => Questions.Count;
    }
}

WebApp3/WebApp3/Controllers/MockupsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApp3.Models;
using WebApp3.Utils;

namespace WebApp3.Controllers
{
    public class MockupsController : Controller
    {
        private int QuestionCount
        {
            get
            {
                return HttpContext.Session.Get<int>(nameof(QuestionCount)) switch
                {
                    < 0 => throw new Exception("Invalid question count"),
                    { } count => count
                };
            }
        }

        private QuizQuestionModel NextQuestion
        {
            get
            {
                var question = QuizQuestionModel.RandomQuizQuestion;

                var count = QuestionCount;
                HttpContext.Session.Set($"Question{count}", question);
                count += 1;
                HttpContext.Session.Set(nameof(QuestionCount), count);

                return question;
            }
        }

        private QuizQuestionModel LastQuestion
        {
            get
            {
                var count = QuestionCount - 1;
                return HttpContext.Session.Get<QuizQuestionModel>($"Question{count}");
            }
        }

        private QuizResultModel Result
        {
            get
            {
                var result = new QuizResultModel { Questions = new() };
                for (var i = 0; i < QuestionCount; i++)
                {
                    var question = HttpContext.Session.Get<QuizQuestionModel>($"Question{i}");
                    result.Questions.Add(question);
                }

                return result;
            }
        }

        private void SaveAnswer(int? answer)
        {
            var lastQuestion = LastQuestion;
            lastQuestion.UserAnswer = answer;
            HttpContext.Session.Set($"Question{QuestionCount - 1}", lastQuestion);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Quiz()
        {
            var question = QuestionCount switch
            {
                0 => NextQuestion,
                _ => LastQuestion
            };
            ViewBag.Question = question.ToString();
            return View();
        }

        [HttpPost]
        public IActionResult Quiz(QuizAnswerModel answerModel, string action)
        {
            if (ModelState.IsValid)
            {
                if (answerModel.Answer < -10)
                {
                    ModelState.AddModelError("Answer", $"  {answerModel.Answer} слишком маленькое число для этого сайта");
                    ViewBag.Question = LastQuestion;
                    return View();
                }
                SaveAnswer(answerModel.Answer);

                if (action == "Next")
                {
                    ViewBag.Question = NextQuestion;
                    return RedirectToAction("Quiz");
                }
                else
                {
                    return RedirectToAction("QuizResult");
                }
            }
            else
            {
                ViewBag.Question = LastQuestion;
                return View();
            }
        }
        public IActionResult QuizResult()
        {
            var result = Result;

            HttpContext.Session.Clear();

            return View(result);
        }
    }
}

WebApp3/WebApp3/Views/Mockups/Index.cshtml
@{
    ViewBag.Title = "Hello Mockups";
}
<h2>Mockups</h2>
<ul>
    <li><a asp-controller="Mockups" asp-action="Quiz">Quiz</a></li>
    <li><a asp-controller="Mockups" asp-action="QuizResult">QuizResult</a></li>
</ul>

WebApp3/WebApp3/Views/Mockups/Quiz.cshtml
@model WebApp3.Models.QuizAnswerModel
@{
    ViewBag.Title = "Quiz";
}

<h2>Quiz</h2>
<b>@ViewBag.Question</b>
<br />
<form asp-controller="Mockups">
    <input asp-for="Answer" class="mb-3 mr-3" /><span asp-validation-for="Answer"></span><br />
    <div class="mb-3">
        <input type="submit" value="Next" name="action" class="btn btn-outline-secondary btn-sm" />
        <input type="submit" value="Finish" name="action" class="btn btn-primary btn-sm" />
    </div>
</form>

WebApp3/WebApp3/Views/Mockups/QuizResult.cshtml
@model WebApp3.Models.QuizResultModel
@{
    ViewBag.Title = "Quiz";
}

<h2>Quiz results</h2>
<h4>Right answers @Model.CorrectAnswerCount out @Model.Count</h4>
<ol>
    @foreach (var question in Model.Questions)
    {
        <li>@question.ToString() @question.UserAnswer</li>
    }
</ol>

WebApp3/WebApp3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Mockups" asp-action="Index">Backend3</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Mockups" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Mockups" asp-action="Index">Mockups</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="container">
        <footer class="border-top footer text-muted">
            &copy; 2022 - Backend3
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>